### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by assada** [thomas-alrek/markov-chain-js#1]
```
node -v
v8.1.3
```

Try to run your exaple and...

```
E:\projects\kiev_leprobot>node test.js
E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?defi
ne([],e):"object"==typeof exports?exports.MarkovChain=e():t.MarkovChain=e()}(this,function(){return function(t){function e(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};r
eturn t[r].call(o.exports,o,o.exports,e),o.l=!0,o.exports}var n={};return e.m=t,e.c=n,e.i=function(t){return t},e.d=function(t,n,r){e.o(t,n)||Object.defineProperty(t,n,{configurable:!1,enu
merable:!0,get:r})},e.n=function(t){var n=t&&t.__esModule?function(){return t.default}:function(){return t};return e.d(n,"a",n),n},e.o=function(t,e){return Object.prototype.hasOwnProperty.
call(t,e)},e.p="",e(e.s=75)}([function(t,e){var n=t.exports={version:"2.4.0"};"number"==typeof __e&&(__e=n)},function(t,e){var n=t.exports="undefined"!=typeof window&&window.Math==Math?win


TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:21135)
    at Object.<anonymous> (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:21140)
    at e (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:388)
    at t.exports.version (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:771)
    at E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:781
    at n (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:143)
    at Object.<anonymous> (E:\projects\kiev_leprobot\node_modules\markov-chain-js\dist\markov-chain.min.js:1:265)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by thomas-alrek** [comment]
Yes I am aware of it. It's an issue with me writing ES6 code and Node not yet supprting ES6 style exports. I am working on a solution

**Comment by greim** [comment]
I managed to work around this by tweaking my require like so:
```js
const MarkovChain = require('markov-chain-js/src/markov-chain');
```
...that way it skips the babelified stuff completely.
