### ISSUE TITLE
Error on code sample

### ISSUE THREAD

**Issue by jkarttunen** [thomas-alrek/markov-chain-js#2]
I'm getting

`> const MarkovChain = require('markov-chain-js')
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (/Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:21073)
    at Object.<anonymous> (/Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:21078)
    at e (/Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:326)
    at /Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:709
    at /Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:719
    at /Users/.../markov/node_modules/markov-chain-js/dist/markov-chain.min.js:1:81
>  `

on import. Maybe this needs a specific node version?

**Comment by foxt** [comment]
Replace `require("markov-chain-js")` with `require("markov-chain-js/src/markov-chain.js");`
Webpack config is broken.

**Comment by Pufikas** [comment]
As @foxt said
> Replace `require("markov-chain-js")` with `require("markov-chain-js/src/markov-chain.js");` Webpack config is broken. 

Since it's resides within  `src/markov-chain.js` folder.

**Comment by thomas-alrek** [comment]
Hello, thanks for pointing out the mistake. I haven't really maintained this repository in several years. Feel free to contribute a PR to fix this, and I will get it merged. Thanks
